project:
  type: website

website:
  title: "tidymodels workshops"
  navbar:
    background: primary
    logo: docs/images/tidymodels.png
    left:
      - href: index.qmd
        text: "Home"
      - text: "Previous Workshops"
        menu:
          - text: "RStudio::conf 2022"
            href: docs/2022-07-RStudio-conf/index.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

