project:
  type: website

website:
  title: "Machine learning with tidymodels"
  description: "This workshop provides an introduction to machine learning with R using the tidymodels framework, a collection of packages for modeling and machine learning using tidyverse principles."
  open-graph: true
  twitter-card: true
  site-url: https://workshops.tidymodels.org
  repo-url: https://github.com/tidymodels/workshops
  repo-actions: [edit, issue]
  page-footer:
    left: |
      Proudly supported by
      [![](https://www.rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-flat.svg){fig-alt="RStudio" width=65px}](https://www.rstudio.com)

  navbar:
    background: "#CA225E"
    logo: tidymodels.png
    right:
      - text: Learn More
        menu:
          - href: https://www.tidymodels.org/start/
            text: "Get started at tidymodels.org"
          - href: https://www.tmwr.org/
            text: "Tidy Modeling with R"
          - href: https://supervised-ml-course.netlify.app/
            text: "Online interactive course"

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

